version: "3.9"
services:
  backend:
    build:
      dockerfile: Dockerfile
      args:
        LOGOUT_URL: https://localhost/saml/logout
        LOGIN_URL: https://localhost/saml/login
    environment:
      - INFERENCE_KEY=123
      - ADMIN_KEY=321
      - MONGO_SESSION_COLLECTION=sessions
      # Indicate where you have a LLM Running.
      - LLM_BASE_URL=https://nginx-server:8001
      - MONGOUSER=test
      - MONGOPASSWORD=test
      - MONGOHOST=mongo
      - REDISHOST=redis
      - REDISPORT=6379
      - GATEWAY_DEBUG=1
      - FRONTEND_URL=https://localhost
      - POPUPLOGIN=1
      - DEV_MODE=1
    container_name: gateway-server
    ports:
      - 127.0.0.1:3000:3000
    depends_on:
      - mongo
      - redis
    volumes:
      - ./app:/app/app
      - ./dev_data/saml:/app/app/security/saml_data
      - ./dev_data/certs:/app/app/security/saml_data/certs
    command: gunicorn app.main:app --bind 0.0.0.0:3000 -k uvicorn.workers.UvicornWorker --workers 1 --reload

  nginx:
    image: docker.io/library/nginx:alpine
    environment:
      - NGINX_HTTPS_PORT=443
      - HOSTNAME=localhost
      - LLM_HOST=http://192.168.0.19:8080
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
    volumes:
      - ./dev_data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./dev_data/nginx/templates:/etc/nginx/templates
      - ./dev_data/certs/sp.crt:/certificates/certificate.crt
      - ./dev_data/certs/sp.key:/certificates/private.key
    depends_on:
      - backend
    container_name: nginx-server
  mongo:
    extends:
      file: docker_databases.yml
      service: mongo
  redis:
    extends:
      file: docker_databases.yml
      service: redis
  mysql:
    extends:
      file: docker_databases.yml
      service: mysql
  keycloak:
    extends:
      file: docker_databases.yml
      service: keycloak
networks:
  default:
    name: inference-network
