name: LLMGateWay
channels:
  - conda-forge
dependencies:
  - fastapi
  - gunicorn
  - uvicorn
  - redis-py
  - pymongo
  - schedule
  - httpx
  - python3-saml
  - python-multipart
  - pip
  - pip:
      - sse-starlette>=1.6.1
