name: LLMGateWay
channels:
  - conda-forge
dependencies:
  - fastapi
  - gunicorn
  - uvicorn
  - redis-py
  - pymongo
  - schedule
  - httpx
  - python3-saml
  - python-multipart
  - python-jose[cryptography]
  - sse-starlette>=1.6.1
  - itsdangerous
  - pip
  - pip:
      - pytest-mock-resources[mongo]
      - pytest-mock-resources[redis]
      - llama-cpp-python[server]==0.2.64
