name: LLMGateWay
channels:
  - conda-forge
dependencies:
  - python=3.12
  - fastapi
  - gunicorn
  - uvicorn
  - redis-py
  - pymongo
  - schedule
  - httpx
  - python3-saml
  - python-multipart
  - python-jose[cryptography]
  - sse-starlette>=1.6.1
  - itsdangerous
  - pip
  - watchfiles==0.24.0
  - pytest-asyncio  
  - pip:
      - pytest-mock-resources[mongo]
      - pytest-mock-resources[redis]
      - mongomock      