name: LLMGateWay-Dev
channels:
  - conda-forge
dependencies:
  - fastapi
  - redis-py
  - pymongo
  - schedule
  - pytest
  - pip
  - pip:
      - pytest-mock-resources[mongo]
      - pytest-mock-resources[redis]
