---
# redis database
apiVersion: apps/v1
kind: Deployment
metadata:
  name: LLM-redis
  namespace: LLMGateway
  labels:
    app: LLM-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: LLM-redis
  template:
    metadata:
      labels:
        app: LLM-redis
    spec:
      containers:
        - name: LMM-redis-db
          image: redis:7.2.3
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: 1
---
# mongo database
apiVersion: apps/v1
kind: Deployment
metadata:
  name: LLM-mongo
  namespace: LLMGateway
  labels:
    app: LLM-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: LLM-mongo
  template:
    metadata:
      labels:
        app: LLM-mongo
    spec:
      containers:
        - name: LLM-mongo-db
          image: mongo:7.0.4
          ports:
            - containerPort: 27017
          resources:
            requests:
              cpu: 1
          env:
            - {
                name: MONGO_INITDB_ROOT_USERNAME,
                valueFrom: { secretKeyRef: { name: mongo, key: user } },
              }
            - {
                name: MONGO_INITDB_ROOT_PASSWORD,
                valueFrom: { secretKeyRef: { name: mongo, key: password } },
              }
          volumeMounts:
            - mountPath: /data/db
              name: LLM-mongo
      volumes:
        - name: LLM-mongo
          persistentVolumeClaim:
            claimName: LLM-mongo
