---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llm-azure-mongo
  namespace: rse
spec:
  storageClassName: nfs-client # Empty string must be explicitly set otherwise default StorageClass will be set
  accessModes: [ReadWriteOnce] # This should only ever be accessed by one mongoDB server instance
  resources:
    requests:
      storage: 1Gi
#---
