---
# hedgedoc itself
apiVersion: apps/v1
kind: Deployment
metadata:
  name: LLM-gateway
  namespace: LLMGateway
  labels:
    app: LLM-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: LLM-gateway
  template:
    metadata:
      labels:
        app: LLM-gateway
    spec:
      containers:
        - name: gateway
          image: harbor.cs.aalto.fi/aaltorse-public/llm_gateway # TODO
          ports:
            - containerPort: 8000
          resources:
            requests:
              # Maybe needs to be increased later on.
              cpu: 2
              memory: "1000Mi"
          env:
            # Mongo settings
            - {
                name: MONGOUSER,
                valueFrom: { secretKeyRef: { name: mongo, key: user } },
              }
            - {
                name: MONGOPASSWORD,
                valueFrom: { secretKeyRef: { name: mongo, key: password } },
              }
            - { name: MONGOHOST, value="LLM-mongo-svc" }
            # Redis
            - { name: REDISHOST, value="LLM-redis-svc" }
            - { name: REDISPORT, value="6379" }
            # Default API key
            - {
                name: DEFAULT_API_KEY,
                valueFrom:
                  { secretKeyRef: { name: llm_gateway, key: gateway_key } },
              }
            - {
                name: INFERENCE_KEY,
                valueFrom:
                  { secretKeyRef: { name: llm_gateway, key: inference_key } },
              }
          #volumeMounts:
          #  - mountPath: /hedgedoc/public/uploads
          #    name: hd-uploads
