---
# Gateway deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-gateway
  namespace: rse
  labels:
    app.kubernetes.io/name: llm-gateway
    app.kubernetes.io/component: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: llm-gateway
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: llm-gateway
        app.kubernetes.io/component: server
    spec:
      volumes:
        - name: certificate-volume
          secret:
            secretName: llm-gatewaysaml-secret
      containers:
        - name: gateway
          image: harbor.cs.aalto.fi/aaltorse-public/llm_gateway:CORS-1.1 #Lets start versioning this
          ports:
            - containerPort: 3000
          resources:
            requests:
              # Maybe needs to be increased later on.
              cpu: 2
          env:
            # Mongo settings ( port will be default )
            - {
                name: MONGOUSER,
                valueFrom: { secretKeyRef: { name: mongo, key: user } },
              }
            - {
                name: MONGOPASSWORD,
                valueFrom: { secretKeyRef: { name: mongo, key: password } },
              }
            - { name: MONGOHOST, value: "llm-mongo-svc" }
            - { name: LLM_BASE_URL, value: "https://llm.k8s-test.cs.aalto.fi" }
            # Redis
            - { name: REDISHOST, value: "llm-redis-svc" }
            - { name: REDISPORT, value: "6379" }
            # This is the admin key, which allows generation/removal of additional keys
            - {
                name: ADMIN_KEY,
                valueFrom:
                  { secretKeyRef: { name: llm-gateway, key: gateway_key } },
              }
            # This is the key for the INFERENCE Server
            - {
                name: INFERENCE_KEY,
                valueFrom:
                  { secretKeyRef: { name: llm-gateway, key: inference_key } },
              }
          volumeMounts:
            - mountPath: /app/saml/saml_data/certs
              name: certificate-volume
              readOnly: true
