"""Initial Migration

Revision ID: 13b7fdc90faf
Revises:
Create Date: 2025-09-23 05:29:51.839917

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "13b7fdc90faf"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llmmodels",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("llm_model_id", sa.String(), nullable=False),
        sa.Column("owned_by", sa.String(), nullable=False),
        sa.Column("permissions", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("object", sa.String(), nullable=False),
        sa.Column("type", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("host", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("prompt_cost", sa.Float(), nullable=False),
        sa.Column("completion_cost", sa.Float(), nullable=False),
        sa.Column("cached_token_cost", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id", "llm_model_id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("llm_model_id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("auth_id", sa.String(length=60), nullable=False),
        sa.Column("first_name", sa.String(length=40), nullable=False),
        sa.Column("last_name", sa.String(length=60), nullable=False),
        sa.Column("admin", sa.Boolean(), nullable=False),
        sa.Column("accepted_agreement_version", sa.String(), nullable=False),
        sa.Column("quota", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("auth_id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "api_keys",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("service", sa.String(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("quota", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("key"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "balance",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("key", sa.String(), nullable=True),
        sa.Column("balance_used", sa.Float(), nullable=False),
        sa.Column("period", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["key"],
            ["api_keys.key"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(op.f("ix_balance_key"), "balance", ["key"], unique=False)
    op.create_index(op.f("ix_balance_user_id"), "balance", ["user_id"], unique=False)
    op.create_table(
        "usage",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("api_key", sa.String(), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("cost", sa.Float(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["api_key"],
            ["api_keys.key"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("usage")
    op.drop_index(op.f("ix_balance_user_id"), table_name="balance")
    op.drop_index(op.f("ix_balance_key"), table_name="balance")
    op.drop_table("balance")
    op.drop_table("api_keys")
    op.drop_table("users")
    op.drop_table("llmmodels")
    # ### end Alembic commands ###
