"""Adding document_set to conversation

Revision ID: 0c48d277e3c5
Revises: 2b9478efe3ef
Create Date: 2025-04-01 05:23:15.078337

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0c48d277e3c5"
down_revision: Union[str, None] = "2b9478efe3ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "conversations", sa.Column("document_set_id", sa.Integer(), nullable=True)
    )
    op.create_index(
        op.f("ix_conversations_document_set_id"),
        "conversations",
        ["document_set_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "conversations", "document_sets", ["document_set_id"], ["id"]
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_conversations_document_set_id"), table_name="conversations")
    op.drop_column("conversations", "document_set_id")

    # ### end Alembic commands ###
