"""Adding selected_language field to user

Revision ID: 08d804907127
Revises: 616ad38220cd
Create Date: 2025-06-19 06:14:08.465388

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "08d804907127"
down_revision: Union[str, None] = "616ad38220cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "users",
        sa.Column(
            "selected_language",
            sa.String(length=10),
            nullable=False,
            default="en",
            server_default="en",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column("users", "selected_language")

    # ### end Alembic commands ###
