apiVersion: v1
kind: Secret
metadata:
  name: llm-gateway-secrets
  namespace: {{ $.Release.Namespace }}
type: Opaque
stringData: 
  admin_key: {{ randAlphaNum 48 | b64enc }}
  session_key: {{ randAlphaNum 48 | b64enc }}  

---
apiVersion: v1
kind: Secret
metadata:
  name: llm-communication-secrets
  namespace: {{ $.Release.Namespace }}
type: Opaque
stringData:
  inference_key: {{ randAlphaNum 48 | b64enc }}
  hf_token: {{ .Values.hf_token }}

---
apiVersion: v1
kind: Secret
metadata:
  name: llm-gateway-databases
  namespace: {{ $.Release.Namespace }}
type: Opaque
stringData: 
  postgresql_user: {{ .Values.postgres_user }}
  postgresql_password: {{ randAlphaNum 48 | b64enc }}
  redispassword: {{ randAlphaNum 48 | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: saml-secret-data
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
  sp.crt: {{ .Values.saml_certificate }}
  sp.key: {{ .Values.saml_private_key }}
