"""Utilities for generating private and public keys for JWT tokens"""

import datetime
import base64
from typing import Any

import jwt

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives.asymmetric.rsa import RSAPrivateKey, RSAPublicKey
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.hazmat.primitives import hashes
from cryptography.x509 import CertificateBuilder, NameOID, Certificate
from cryptography import x509


from app.schemas.user_schema import User
from app.security.entra_jwt import JWKS, EntraJWTAuthService

TENANT_ID = "ae1a7724-4041-4462-a6dc-538cb199707e"  # Aalto's tenant ID
AUDIENCE = "api://f9f02fa3-9d55-422b-9dd1-1942471b27c4"  # App ID

STUDENT_DEGREE_GROUP_1 = "f92054ea-0968-47f1-bce8-9c0f94d65f1e"
STUDENT_DEGREE_GROUP_2 = "69a0bbf2-3f37-458c-810e-d8457cb2a9e3"
STAFF_GROUP_1 = "3ab7ddd2-16f3-4736-853c-f1f7f2c00c68"

# Example usage
KEY_ID = "example_kid"


def get_test_entra_auth_instance() -> EntraJWTAuthService:
    return EntraJWTAuthService(
        tenant_id=TENANT_ID,
        audience=AUDIENCE,
        role_map={
            STUDENT_DEGREE_GROUP_1: "student_degree",
            STUDENT_DEGREE_GROUP_2: "student_degree",
            STAFF_GROUP_1: "staff",
        },
        valid_scopes=["AaltoAI.Access"],
        insecure_predefined_keys=jwks,
    )


def create_rsa_key_pair() -> tuple[RSAPrivateKey, RSAPublicKey]:
    private_key = rsa.generate_private_key(
        public_exponent=65537, key_size=2048, backend=default_backend()
    )
    public_key = private_key.public_key()

    return private_key, public_key


priv_key, pub_key = create_rsa_key_pair()


def generate_self_signed_cert(
    private_key: RSAPrivateKey, public_key: RSAPublicKey
) -> Certificate:
    subject = issuer = x509.Name(
        [
            x509.NameAttribute(NameOID.COUNTRY_NAME, "US"),
            x509.NameAttribute(NameOID.STATE_OR_PROVINCE_NAME, "California"),
            x509.NameAttribute(NameOID.LOCALITY_NAME, "San Francisco"),
            x509.NameAttribute(NameOID.ORGANIZATION_NAME, "My Company"),
            x509.NameAttribute(NameOID.COMMON_NAME, "mycompany.com"),
        ]
    )
    certificate = (
        CertificateBuilder()
        .subject_name(subject)
        .issuer_name(issuer)
        .public_key(public_key)
        .serial_number(x509.random_serial_number())
        .not_valid_before(datetime.datetime.now(datetime.timezone.utc))
        .not_valid_after(
            datetime.datetime.now(datetime.timezone.utc) + datetime.timedelta(days=365)
        )
        .add_extension(
            x509.SubjectAlternativeName([x509.DNSName("localhost")]),
            critical=False,
        )
        .sign(private_key, hashes.SHA256())
    )
    return certificate


def get_key_components(public_key: RSAPublicKey) -> tuple[str, str]:
    numbers = public_key.public_numbers()
    generated_n = (
        base64.urlsafe_b64encode(
            numbers.n.to_bytes((numbers.n.bit_length() + 7) // 8, byteorder="big")
        )
        .decode("utf-8")
        .rstrip("=")
    )
    generated_e = (
        base64.urlsafe_b64encode(
            numbers.e.to_bytes((numbers.e.bit_length() + 7) // 8, byteorder="big")
        )
        .decode("utf-8")
        .rstrip("=")
    )
    return generated_n, generated_e


cert = generate_self_signed_cert(priv_key, pub_key)
n, e = get_key_components(pub_key)
x5c = [base64.b64encode(cert.public_bytes(serialization.Encoding.DER)).decode("utf-8")]

jwks: JWKS = {
    "keys": [
        {
            "kty": "RSA",
            "use": "sig",
            "kid": KEY_ID,
            "x5t": KEY_ID,
            "n": n,
            "e": e,
            "x5c": x5c,
            "cloud_instance_name": "microsoftonline.com",
            "issuer": f"https://login.microsoftonline.com/{TENANT_ID}/v2.0",
        },
    ]
}


def create_jwt_token(  # pylint: disable=too-many-arguments
    private_key: RSAPrivateKey,
    auth_id: str,
    groups: list[str],
    exp: datetime.timedelta = datetime.timedelta(hours=1),
    first: str = "John",
    last: str = "Doe",
    field_set: dict[str, Any] | None = None,
    key_id: str | None = KEY_ID,
) -> str:
    """
    sample token as generated by Entra ID for Aalto AI:

    {
        'aud': 'api://f9f02fa3-9d55-422b-9dd1-1942471b27c4',
        'iss': 'https://sts.windows.net/ae1a7724-4041-4462-a6dc-538cb199707e/',
        'iat': 1742285333,
        'nbf': 1742285333,
        'exp': 1742289422,
        'acr': '1',
        'aio': '[long base64 encoded code]',
        'amr': ['mfa'],
        'appid': 'f9f02fa3-9d55-422b-9dd1-1942471b27c4',
        'appidacr': '0',
        'family_name': 'Lastname',
        'given_name': 'Firstname',
        'groups': ['406a54fc-6ee1-4909-8ebe-280381547528', '3ab7ddd2-16f3-4736-853c-f1f7f2c00c68', 'b050d1ca-73db-4045-8534-6288a93dab89', '06380dba-3e56-45e4-bbf4-37235a864775'],
        'ipaddr': '2001:708:....[rest]',
        'name': 'Lastname Firstname',
        'oid': '[uuid]',
        'onprem_sid': 'S-1-5-21-2413826791-....',
        'rh': '1.something.',
        'scp': 'AaltoAI.Access',
        'sid': '[uuid]
        'sub': '[value]
        'tid': '[uuid]
        'unique_name': 'email@aalto.fi',
        'upn': 'email@aalto.fi',
        'uti': '[value]',
        'ver': '1.0'
    }
    """

    if field_set is None:
        field_set = {}

    now = datetime.datetime.now(datetime.timezone.utc)
    payload: dict[str, Any] = {
        "scp": "AaltoAI.Access",
        "groups": groups,
        "given_name": first,
        "family_name": last,
        "unique_name": auth_id,
        "aud": AUDIENCE,
        "iss": f"https://sts.windows.net/{TENANT_ID}/",
        "iat": now,
        "exp": now + exp,
        "ver": "1.0",
        "tid": TENANT_ID,
    }

    for field, value in field_set.items():
        if value is None:
            del payload[field]
        else:
            payload[field] = value

    headers = {}
    if key_id is not None:
        headers["kid"] = key_id

    token = jwt.encode(payload, private_key, algorithm="RS256", headers={"kid": key_id})

    return token


def create_user_token(  # pylint: disable=too-many-arguments
    auth_id: str,
    groups: list[str],
    first: str = "John",
    last: str = "Doe",
    timedelta: datetime.timedelta = datetime.timedelta(hours=1),
    private_key: RSAPrivateKey = priv_key,
    field_set: dict[str, Any] | None = None,
    key_id: str | None = KEY_ID,
) -> str:
    return create_jwt_token(
        private_key=private_key,
        auth_id=auth_id,
        groups=groups,
        exp=timedelta,
        first=first,
        last=last,
        field_set=field_set,
        key_id=key_id,
    )


def create_token_for_user(
    user: User,
    roles: list[str],
    private_key: RSAPrivateKey = priv_key,
    timedelta: datetime.timedelta = datetime.timedelta(hours=1),
    field_set: dict[str, Any] | None = None,
    key_id: str | None = KEY_ID,
) -> str:
    return create_user_token(
        auth_id=user.auth_id,
        groups=roles,
        first=user.first_name,
        last=user.last_name,
        timedelta=timedelta,
        private_key=private_key,
        field_set=field_set,
        key_id=key_id,
    )
